apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-logging
  labels:
    app: elasticsearch-logging
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-logging
  template:
    metadata:
      labels:
        app: elasticsearch-logging
    spec:
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: registry.forensix.cn/docker/elasticsearch:6.5.4
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx4g"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: esdata
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch-logging
