---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-server-config
  labels:
    k8s-app: fluentd-server
  namespace: logging
data:
  fluent.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match *.**>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch
        port 9200
        logstash_format true
        logstash_prefix fluentd
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        flush_interval 1s
      </store>
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-server
  labels:
    app: fluentd-server
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-server
  template:
    metadata:
      labels:
        app: fluentd-server
    spec:
      containers:
      - name: fluentd-server
        image: registry.forensix.cn/docker/fluentd:v1.3.0-elasticsearch
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: fluentd-server-config
          mountPath: /fluentd/etc/fluent.conf
          readOnly: true
          subPath: fluent.conf
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
      volumes:
      - name: fluentd-server-config
        configMap:
          name: fluentd-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    app: fluentd-server
  ports:
    - port: 24224
      targetPort: 24224
