kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-fs-test
  namespace: default
spec:
  storageClassName: ceph-fs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
