kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.1.90:6789
  adminId: kuber
  adminSecretName: ceph-secret-kuber
  adminSecretNamespace: kube-system
  pool: kube
  userId: kuber
  userSecretName: ceph-secret-kuber
  userSecretNamespace: kube-system
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
reclaimPolicy: Retain
