kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-fs
provisioner: ceph.com/cephfs
parameters:
    monitors: 192.168.1.90:6789
    adminId: cephfs
    adminSecretName: ceph-secret-cephfs
    adminSecretNamespace: kube-system
    claimRoot: /volumes/kubernetes
reclaimPolicy: Retain
